services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks: 
    - app-network
    ports:
      - "8080:8080"
    container_name: backend-container

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      BACKEND_URL: http://backend:8080
    networks: 
    - app-network
    ports:
      - "8501:8501"
    container_name: frontend-container

networks:
  app-network:
    driver: bridge